version: '{branch}-{build}'
build: off
image: Visual Studio 2019
environment:
  matrix:
    - PYTHON_HOME: "C:\\Python38-x64"
    - PYTHON_HOME: "C:\\Python39-x64"
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - "%PYTHON_HOME%\\python -m pip install --upgrade pip"
  - "%PYTHON_HOME%\\python -m pip install -r ci/requirements.txt"
  - "%PYTHON_HOME%\\python -m pip install tox"

test_script:
  - "%PYTHON_HOME%\\python -m tox"

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
